/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_listpelanggan;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author tauhid
 */
public class JFLPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form JFLPelanggan
     */
    c_listpelanggan pelanggan;
    JFPenjualan jual;
    
    public JFLPelanggan(JFPenjualan jual) {
        initComponents();
        this.setTitle("List Pelanggan");
        this.setLocationRelativeTo(getRootPane());
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        
        pelanggan = new c_listpelanggan(this);
        pelanggan.isiTabel();
        this.jual = jual;
    }

        public JTable getDataTable(){
        return jTable2;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jbCariPenyakit1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(250, 300));

        jPanel3.setPreferredSize(new java.awt.Dimension(333, 25));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jbCariPenyakit1.setText("Pilih");
        jbCariPenyakit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCariPenyakit1ActionPerformed(evt);
            }
        });
        jPanel3.add(jbCariPenyakit1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCariPenyakit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCariPenyakit1ActionPerformed
        // TODO add your handling code here
        if (jTable2.getSelectedRow()>=0){
            jual.getKodePelanggan().setText(jTable2.getValueAt(jTable2.getSelectedRow(),1).toString());
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Hama Pada Tabel","Pesan Kesalahan",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jbCariPenyakit1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton jbCariPenyakit;
    private javax.swing.JButton jbCariPenyakit1;
    // End of variables declaration//GEN-END:variables
}
