/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import controller.c_pelanggan;
import javax.swing.JOptionPane;

/**
 *
 * @author tauhid
 */
public class JFPelanggan extends javax.swing.JFrame {

    c_pelanggan pelanggan;
    
    /**
     * Creates new form JFPelanggan
     */
    public JFPelanggan() {
        initComponents();
        this.setTitle("Data Pelanggan");
        this.setLocationRelativeTo(getRootPane());
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.ID.setVisible(false);
        pelanggan = new c_pelanggan(this);
        pelanggan.isiTabel();
    }

    public JTable getDataTable(){ return jTable1; }
    public JTextField getKode(){ return jTextField1; }
    public JTextField getNama(){ return jTextField2; }
    public JTextField getAlamat(){ return jTextField3; }
    public JTextField getHp(){ return jTextField4; }
    public JLabel getID(){ return ID; }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_tabel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_form = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_tabel.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Pelanggan"));
        panel_tabel.setPreferredSize(new java.awt.Dimension(400, 150));
        panel_tabel.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        panel_tabel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_tabel, java.awt.BorderLayout.CENTER);

        panel_form.setPreferredSize(new java.awt.Dimension(400, 200));
        panel_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Kode");
        panel_form.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Nama");
        panel_form.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        panel_form.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 180, -1));

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel_form.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel_form.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel_form.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));
        panel_form.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 180, -1));

        jLabel3.setText("Alamat");
        panel_form.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel4.setText("Handphone");
        panel_form.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        ID.setText("IDX");
        panel_form.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));
        panel_form.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 180, -1));
        panel_form.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 180, -1));

        getContentPane().add(panel_form, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        ID.setText(jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
        jTextField1.setText(jTable1.getValueAt(jTable1.getSelectedRow(),1).toString());
        jTextField2.setText(jTable1.getValueAt(jTable1.getSelectedRow(),2).toString());
        jTextField3.setText(jTable1.getValueAt(jTable1.getSelectedRow(),3).toString());
        jTextField4.setText(jTable1.getValueAt(jTable1.getSelectedRow(),4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pelanggan.insert(this);
        pelanggan.isiTabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        pelanggan.update(this);
        pelanggan.isiTabel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow()>=0){
            int dialogResult = JOptionPane.showConfirmDialog (this, "Anda Yakin Akan Menghapus Data Ini?","Peringatan",JOptionPane.WARNING_MESSAGE);
            if(dialogResult == JOptionPane.YES_OPTION){
                String id = jTable1.getValueAt(jTable1.getSelectedRow(),0).toString();
                pelanggan.delete(id);
                pelanggan.isiTabel();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Pada Tabel Sebelum Hapus","Pesan Kesalahan",JOptionPane.WARNING_MESSAGE);
        }         
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panel_form;
    private javax.swing.JPanel panel_tabel;
    // End of variables declaration//GEN-END:variables
}
